### ISSUE TITLE
通过start.aliyun.com选Sentinel示例的时候页面会空白

### ISSUE THREAD

**Issue by xvm03** [alibaba/cloud-native-app-initializer#10]
通过start.aliyun.com选Sentinel示例的时候页面会空白

**Comment by theonefx** [comment]
我们会在近期内，会使用开源版本的代码对 start.aliyun.com 做一下升级，届时这些问题应该都可以得到解决

**Comment by guluwj** [comment]
> 我们会在近期内，使用开源版的代码对start.aliyun.com做一下升级，届时这些问题应该都能得到解决
貌似这个问题现在还是存在哦

**Comment by steverao** [comment]
已经完成了升级，当前已经将示例代码跟组件绑定到一起了，选择组件后，会自动添加上相关的示例代码，已经没有了上述问题。
