### ISSUE TITLE
"start.aliyun.com" is unavailable

### ISSUE THREAD

**Issue by anncfei** [alibaba/cloud-native-app-initializer#102]
Why does the URL "https://start.aliyun.com" appear blank in a browser

**Comment by dxpixx** [comment]
什么时候能修好啊

**Comment by dxpixx** [comment]
> Why does the URL "https://start.aliyun.com" appear blank in a browser

我也访问不了了

**Comment by anncfei** [comment]
Scaffolding is now accessible
