### ISSUE TITLE
Prioritize the use of dependModules when both dependModules and main are satisfied

### ISSUE THREAD

**Issue by weixsun** [alibaba/cloud-native-app-initializer#24]
CN:
我们正在定制一套适合自己的多模块的层次结构，发现当其中一个模块作为main 存在时即`subModules: main: true`，那么当前脚手架总是会依赖其他所有子模块，即使我定义了`subModules: dependModules: "xxx"`。

我打算提一个pr(作为"enhancement"标签存在)以此来更改它两的优先级使用关系：当`dependModules` 和`main` 同时满足时，优先依赖使用`dependModules`配置的模块，而`main`作为第二序列使用。

**Comment by theonefx** [comment]
Good idea, The rule that main depends on all submodules is a bit too rigid.
