### ISSUE TITLE
关于Springboot3.0版本的问题

### ISSUE THREAD

**Issue by laowang6984** [alibaba/cloud-native-app-initializer#4]
目前脚手架页面显示的还是只有Springboot3.0版本一下的，什么时候能支持springboot3.0呢

**Comment by theonefx** [comment]
We will be supporting this feature in a few days.

**Comment by theonefx** [comment]
Currently, the latest code supports spring 3.0.
Then start.aliyun.com needs to refactor to use latest code, it will need a few weeks.
