### ISSUE TITLE
本地运行项目没有“示例代码”功能

### ISSUE THREAD

**Issue by caominhua** [alibaba/cloud-native-app-initializer#50]
当前github上代码没有和https://start.aliyun.com/同步吗。本地运行启动访问没有“示例代码”功能，是否能同步更新。

**Comment by MingJunDuan** [comment]
同问

**Comment by lishe139** [comment]
同问，还有 分层架构 功能

**Comment by steverao** [comment]
目前因为一些原因，架构暂未统一，社区会尽快将两者进行统一。请稍等！

**Comment by steverao** [comment]
当前已经完成了开源版本跟start.aliyun.com网站代码保持一致，欢迎大家体验！
