### ISSUE TITLE
是否支持扩展项目模板和在线配置查询和修改

### ISSUE THREAD

**Issue by hehuang139** [alibaba/cloud-native-app-initializer#7]
如题，在start.aliyun.com,能看到示例代码，在开源版本中没有，后续这块是否支持自定义的项目模板
同时目前没有看到可以查看特定配置的地方，比如说特定mybatis-plus的配置，可以在代码生成之前显示最佳实践的配置，并支持在线修改，在生成代码，并且查看配置，可以单独显示特定依赖的配置，而不是看全局的配置

**Comment by theonefx** [comment]
目前 start.aliyun.com 的代码是比较旧的，后面会用开源版本的更新。
不过修改生成后的代码，再获取，这个逻辑目前不支持，你可以获取到本地再修改。

**Comment by hehuang139** [comment]
后续这块是否支持自定义的项目模板，默认大于配置，项目模板还是很重要的，如果只是依赖管理，会增加使用的代价。
如果不支持的话，需要以什么方式支持，我们的项目希望是能够使用项目模板，可以将我们自己的项目类型沉淀下来

**Comment by theonefx** [comment]
这个看起来是一个很不错的建议，如果单纯通过抽象和代码实现整个项目所有信息的生成有些不太现实。
用一套模板的概念，确实可以解决很多很现实的问题。
