### ISSUE TITLE
特性咨询

### ISSUE THREAD

**Issue by hehuang139** [alibaba/cloud-native-app-initializer#8]
1. 是否支持扩展第三方的依赖，比如说自己开发的starter，或者initializer中没有的依赖
2. 代码自动生成能力

**Comment by theonefx** [comment]
1. 当然是支持的，我们会在近期提供相关的操作指引。
2. 不是很清楚这个问题的意思，你可以描述一下你想达到的效果吗？

**Comment by hehuang139** [comment]
@theonefx 代码自动生成，比如说类似mybatis-plus的代码自动生成。可能需要的是分层结构 的代码生成

**Comment by steverao** [comment]
> @theonefx 代码自动生成，比如说类似mybatis-plus的代码自动生成。可能需要的是分层结构 的代码生成

目前我们已经提供了分层结构的项目创建初始能力，其中包括生成一些示例代码，比如Nacos服务注册和消费等，具体你可以到：start.aliyun.com 网站中进行体验。

**Comment by steverao** [comment]
Long time without response and close first.
