### ISSUE TITLE
default springboot application got wrong message in index.html

### ISSUE THREAD

**Issue by lousaibiao** [alibaba/cloud-native-app-initializer#93]
**Describe the bug**
Default springboot application got wrong message in index.html. 
It should be hello world!!! not hello word!!!

**Screenshots**
![image](https://github.com/alibaba/cloud-native-app-initializer/assets/5031223/72c82ad1-aaab-4f6b-acff-2b8171fa6965)

**Comment by ralf0131** [comment]
Would you please send a pull request?
